# Generated by Django 4.0.1 on 2022-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=40)),
                ('Date', models.DateTimeField(blank=True, default=None, null=True)),
                ('faze', models.CharField(max_length=40)),
                ('productid', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=40)),
                ('action', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
    ]
