# Generated by Django 4.0.1 on 2022-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketBot', '0003_rename_date_orders_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='buket_arhiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('chatid', models.CharField(max_length=40)),
                ('productid', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=40)),
                ('action', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'buket_arhiv',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='action',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
