# Generated by Django 4.0.1 on 2022-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketBot', '0004_buket_arhiv_remove_orders_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
