# Generated by Django 4.0.1 on 2022-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketBot', '0007_orders_youmoneyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='продукт',
            name='Отключить_продукт',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
