# Generated by Django 4.0.1 on 2022-02-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venipbot', '0003_addresses_basket_usecategory_акции_категория_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addresses',
        ),
        migrations.DeleteModel(
            name='basket',
        ),
        migrations.DeleteModel(
            name='UseCategory',
        ),
        migrations.DeleteModel(
            name='Акции',
        ),
        migrations.RemoveField(
            model_name='подкатегория',
            name='Категория',
        ),
        migrations.RemoveField(
            model_name='продукт',
            name='Категория',
        ),
        migrations.RemoveField(
            model_name='продукт',
            name='Подкатегория',
        ),
        migrations.DeleteModel(
            name='Категория',
        ),
        migrations.DeleteModel(
            name='Подкатегория',
        ),
        migrations.DeleteModel(
            name='Продукт',
        ),
    ]
